FROM arm64v8/alpine@sha256:cc99de154757eb3d8b9200868d0bab96bff581a4f3000e62caed7baf46b41f95

WORKDIR ../

ARG TARGET_ARCH
ARG PACT_CLI_VERSION
ARG TARGET_ARCH=${TARGET_ARCH:-arm64}
ARG PACT_CLI_VERSION=${PACT_CLI_VERSION:-2.0.1}

RUN apk --no-cache add gcompat libc6-compat

RUN wget -q https://github.com/pact-foundation/pact-standalone/releases/download/v${PACT_CLI_VERSION}/pact-${PACT_CLI_VERSION}-linux-${TARGET_ARCH}.tar.gz \
     && tar xzf pact-${PACT_CLI_VERSION}-linux-${TARGET_ARCH}.tar.gz \
     && rm -rf pact-${PACT_CLI_VERSION}-linux-${TARGET_ARCH}.tar.gz \
     && ln -s /pact/bin/* /usr/local/bin

ENTRYPOINT ["pact-mock-service"]