FROM --platform=linux/amd64 ruby:3.4.10-alpine@sha256:6acf053b0254716d793f1e72030742f1b3bf665fd343aed3df15d3e449d06b76

# Installation path
ENV HOME=/app
WORKDIR $HOME

RUN set -ex && \
  adduser -h $HOME -s /bin/false -D -S -G root ruby && \
  chmod g+w $HOME && \
  apk add --update --no-cache make gcc libc-dev

RUN gem install bundler -v "~> 2.5"
COPY packaging/Gemfile packaging/Gemfile.lock $HOME/
RUN bundle install --no-cache
