FROM --platform=linux/amd64 ruby:3.4.11-alpine@sha256:ae2f369670fbf93cc819f299d56af471db6e2223f05268a04fa3fa8b21d8fb65

# Installation path
ENV HOME=/app
WORKDIR $HOME

RUN set -ex && \
  adduser -h $HOME -s /bin/false -D -S -G root ruby && \
  chmod g+w $HOME && \
  apk add --update --no-cache make gcc libc-dev

RUN gem install bundler -v "~> 2.5"
COPY packaging/Gemfile packaging/Gemfile.lock $HOME/
RUN bundle install --no-cache
