source 'https://rubygems.org'

gem "pact", "1.67.5"
gem "pact-message", "0.11.1"
gem "pact-mock_service", "3.12.4"
gem "pact-provider-verifier", "1.39.1"
gem "pact_broker-client", "1.77.0"
gem "webrick", "1.9.2"
# see https://stdgems.org/ for versions to lock to
# we require gem locking for gems with native extensions
# due to lack of windows support
gem "json", "2.7.2"
gem "bigdecimal", "3.1.5"
gem "fiddle", "1.1.2"
gem "io-console", "0.7.1"