name: Update

on:
  repository_dispatch:
    types:
      - gem-released

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      with:
        fetch-depth: 0

    - uses: ruby/setup-ruby@762794c140bbeda0f1224786aa33b4b46783a6c1 # v1.326.0
      with:
        ruby-version: 3.4.10

    - name: Set up environment
      run: |
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global push.default current
        bundler -v
        bundle install

    - name: Update Gemfile
      run: script/update-in-github-workflow.sh
      env:
        RELEASED_GEM_NAME: ${{ github.event.client_payload.name }}
        RELEASED_GEM_VERSION: ${{ github.event.client_payload.version }}

    - name: Trigger release
      uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # v4
      with:
        token: ${{ secrets.GHTOKENFORRELEASEDISPATCH }}
        event-type: release-triggered
